<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260409184140 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE schedules (sch_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sch_day VARCHAR(255) NOT NULL, sch_open_time TIME(0) WITHOUT TIME ZONE NOT NULL, sch_close_time TIME(0) WITHOUT TIME ZONE NOT NULL, sch_max_people INT NOT NULL, sch_is_close BOOLEAN NOT NULL, sch_created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sch_updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (sch_id))');
        $this->addSql('CREATE TABLE specials_schedules (spe_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, spe_date DATE NOT NULL, spe_open_time TIME(0) WITHOUT TIME ZONE NOT NULL, spe_close_time TIME(0) WITHOUT TIME ZONE NOT NULL, spe_is_closed BOOLEAN NOT NULL, spe_max_people INT NOT NULL, spe_created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, spe_updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, spe_deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (spe_id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE schedules');
        $this->addSql('DROP TABLE specials_schedules');
    }
}
