<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260414214627 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE allergens (allergen_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, allergen_name VARCHAR(40) NOT NULL, allergen_info TEXT NOT NULL, allergen_created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, allergen_updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, allergen_deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (allergen_id))');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE categories (category_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, category_name VARCHAR(50) NOT NULL, category_created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, category_updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, category_deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (category_id))');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE cats (cat_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cat_name VARCHAR(40) NOT NULL, cat_birthdate DATE NOT NULL, cat_description TEXT NOT NULL, cat_img VARCHAR(255) NOT NULL, cat_gender VARCHAR(255) NOT NULL, cat_created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, cat_updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cat_deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cat_product INT DEFAULT NULL, PRIMARY KEY (cat_id))');
        $this->addSql('CREATE INDEX idx_c39dba92f3fb86fb ON cats (cat_product)');
        $this->addSql('ALTER TABLE cats ADD CONSTRAINT fk_c39dba92f3fb86fb FOREIGN KEY (cat_product) REFERENCES products (product_id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE ingredients (ingredient_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ingredient_name VARCHAR(50) NOT NULL, ingredient_is_vegan BOOLEAN NOT NULL, ingredient_created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ingredient_updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ingredient_deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (ingredient_id))');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE ingredients_allergens (ing_alg_ingredient INT NOT NULL, ing_alg_allergen INT NOT NULL, PRIMARY KEY (ing_alg_ingredient, ing_alg_allergen))');
        $this->addSql('CREATE INDEX idx_6886b58eee8953ac ON ingredients_allergens (ing_alg_ingredient)');
        $this->addSql('CREATE INDEX idx_6886b58e575230a6 ON ingredients_allergens (ing_alg_allergen)');
        $this->addSql('ALTER TABLE ingredients_allergens ADD CONSTRAINT fk_6886b58eee8953ac FOREIGN KEY (ing_alg_ingredient) REFERENCES ingredients (ingredient_id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ingredients_allergens ADD CONSTRAINT fk_6886b58e575230a6 FOREIGN KEY (ing_alg_allergen) REFERENCES allergens (allergen_id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE products (product_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product_name VARCHAR(100) NOT NULL, product_price NUMERIC(6, 2) NOT NULL, product_img VARCHAR(255) NOT NULL, product_description TEXT NOT NULL, product_period_start DATE DEFAULT NULL, product_period_end DATE DEFAULT NULL, product_created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, product_updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, product_deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, product_category INT NOT NULL, PRIMARY KEY (product_id))');
        $this->addSql('CREATE INDEX idx_b3ba5a5acdfc7356 ON products (product_category)');
        $this->addSql('ALTER TABLE products ADD CONSTRAINT fk_b3ba5a5acdfc7356 FOREIGN KEY (product_category) REFERENCES categories (category_id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE products_ingredients (prd_ing_product INT NOT NULL, prd_ing_ingredient INT NOT NULL, PRIMARY KEY (prd_ing_product, prd_ing_ingredient))');
        $this->addSql('CREATE INDEX idx_b1bd73d444be91bc ON products_ingredients (prd_ing_product)');
        $this->addSql('CREATE INDEX idx_b1bd73d4c0adf9fa ON products_ingredients (prd_ing_ingredient)');
        $this->addSql('ALTER TABLE products_ingredients ADD CONSTRAINT fk_b1bd73d444be91bc FOREIGN KEY (prd_ing_product) REFERENCES products (product_id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE products_ingredients ADD CONSTRAINT fk_b1bd73d4c0adf9fa FOREIGN KEY (prd_ing_ingredient) REFERENCES ingredients (ingredient_id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE reservations (reserv_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reserv_time_slot TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reserv_nb_people INT NOT NULL, reserv_is_canceled BOOLEAN NOT NULL, reserv_created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reserv_updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, reserv_user INT NOT NULL, PRIMARY KEY (reserv_id))');
        $this->addSql('CREATE INDEX idx_4da2391b3abab4 ON reservations (reserv_user)');
        $this->addSql('ALTER TABLE reservations ADD CONSTRAINT fk_4da2391b3abab4 FOREIGN KEY (reserv_user) REFERENCES "user" (user_id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE reset_password_requests (reset_pwd_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reset_pwd_usr_id INT NOT NULL, PRIMARY KEY (reset_pwd_id))');
        $this->addSql('CREATE INDEX idx_16646b41d200243e ON reset_password_requests (reset_pwd_usr_id)');
        $this->addSql('ALTER TABLE reset_password_requests ADD CONSTRAINT fk_16646b41d200243e FOREIGN KEY (reset_pwd_usr_id) REFERENCES "user" (user_id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE schedules (sch_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sch_day VARCHAR(255) NOT NULL, sch_open_time TIME(0) WITHOUT TIME ZONE NOT NULL, sch_close_time TIME(0) WITHOUT TIME ZONE NOT NULL, sch_max_people INT NOT NULL, sch_is_close BOOLEAN NOT NULL, sch_created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sch_updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (sch_id))');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE specials_schedules (spe_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, spe_date DATE NOT NULL, spe_open_time TIME(0) WITHOUT TIME ZONE NOT NULL, spe_close_time TIME(0) WITHOUT TIME ZONE NOT NULL, spe_is_closed BOOLEAN NOT NULL, spe_max_people INT NOT NULL, spe_created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, spe_updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, spe_deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (spe_id))');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE "user" (user_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_email VARCHAR(180) NOT NULL, user_roles JSON NOT NULL, user_pwd VARCHAR(255) NOT NULL, user_lastname VARCHAR(160) NOT NULL, user_firstname VARCHAR(160) NOT NULL, user_is_ban BOOLEAN NOT NULL, user_created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_verified BOOLEAN NOT NULL, PRIMARY KEY (user_id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_identifier_email ON "user" (user_email)');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('CREATE TABLE users_allergens (usr_alg_user INT NOT NULL, usr_alg_allergen INT NOT NULL, PRIMARY KEY (usr_alg_user, usr_alg_allergen))');
        $this->addSql('CREATE INDEX idx_18ae5554c2a62b2 ON users_allergens (usr_alg_allergen)');
        $this->addSql('CREATE INDEX idx_18ae555ac993762 ON users_allergens (usr_alg_user)');
        $this->addSql('ALTER TABLE users_allergens ADD CONSTRAINT fk_18ae555ac993762 FOREIGN KEY (usr_alg_user) REFERENCES "user" (user_id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE users_allergens ADD CONSTRAINT fk_18ae5554c2a62b2 FOREIGN KEY (usr_alg_allergen) REFERENCES allergens (allergen_id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE "allergens"');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE "categories"');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE "cats"');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE "ingredients"');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE "ingredients_allergens"');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE "messenger_messages"');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE "products"');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE "products_ingredients"');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE "reservations"');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE "reset_password_requests"');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE "schedules"');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE "specials_schedules"');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE "user"');
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL120Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL120Platform'."
        );

        $this->addSql('DROP TABLE "users_allergens"');
    }
}
